config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('room/', include('room.urls')),
]

room/urls.py
from django.urls import path

from . import views

app_name = 'room'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:theme_id>/', views.detail, name='detail'),
]

room/models.py
from django.db import models

# Create your models here.

# 기존 db와 연동하는 경우:
# 1. python manage.py inspectdb 로 확인 및 복사하여 class 생성
# # settings.py - INSTALLED_APPS 에 app class 추가
# 2. python manage.py makemigrations
# 3. python manage.py migrate / 또는 python manage.py migrate --fake


class EscapeJbStats(models.Model):
    cafe_id = models.SmallIntegerField(blank=True, null=True)
    cafe_name = models.CharField(max_length=63, blank=True, null=True)
    location_category = models.CharField(max_length=15, blank=True, null=True)
    location_detail = models.CharField(max_length=63, blank=True, null=True)
    home_url = models.CharField(max_length=255, blank=True, null=True)
    # primary_key가 db에 설정이 안되어있는 경우 직접 입력해야 함
    # theme_id = models.SmallIntegerField(blank=True, null=True)
    theme_id = models.SmallIntegerField(primary_key=True)
    theme_name = models.CharField(max_length=63, blank=True, null=True)
    genre = models.CharField(max_length=63, blank=True, null=True)
    activity = models.CharField(max_length=15, blank=True, null=True)
    recom_user = models.CharField(max_length=15, blank=True, null=True)
    review_n = models.BigIntegerField()
    star_stat = models.DecimalField(max_digits=6, decimal_places=5, blank=True, null=True)
    medal_stat = models.DecimalField(max_digits=7, decimal_places=4, blank=True, null=True)
    diff_stat = models.DecimalField(max_digits=7, decimal_places=4, blank=True, null=True)
    success_rate = models.DecimalField(max_digits=7, decimal_places=4, blank=True, null=True)
    left_stat = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    limit_time = models.SmallIntegerField(blank=True, null=True)
    hint_use = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    review_updated = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'escape_jb_stats'

room/views.py
from django.shortcuts import render, get_object_or_404
from .models import EscapeJbStats

# Create your views here.


def index(request):
    # return HttpResponse('안녕하세요. roomona에 오신것을 환영합니다!')
    theme_list = EscapeJbStats.objects.order_by('-star_stat')
    context = {'theme_list': theme_list}
    return render(request, 'room/theme_list.html', context)


def detail(request, theme_id):
    # theme_detail = get_object_or_404(EscapeJbStats.objects.filter(theme_id=theme_id))  # 오브젝트로 가져오는 경우 처리방법 확인 필요
    theme_detail = EscapeJbStats.objects.filter(theme_id=theme_id)
    context = {'theme_detail': theme_detail.values()[0],
               'theme_detail_tup': theme_detail.values_list()[0],
               'test': [k + ': ' + str(theme_detail.values()[0][k]) for k in theme_detail.values()[0]]}
    return render(request, 'room/theme_detail.html', context)

templates/room/theme_detail.html
<div>
    <h2> {{ theme_detail.theme_name }} </h2>

    {% for t in test %}
    <li> {{ t }} </li>
    {% endfor %}

    <br><br><br>
    {{ theme_detail }}
<!--필터로 처리 예정-->
    {% for field in theme_detail %}
    <li> {{ field }}: theme_detail.{{ field }} </li>
    {% endfor %}

    {% for value in theme_detail.values %}
    <li> {{ value }} </li>
    {% endfor %}


</div>

templates/room/theme_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호<br>지역</th>
            <th>테마명<br>매장명</th>
            <th>별점<br>난이도</th>
        </tr>
        </thead>
        <tbody>
        {% if theme_list %}
        {% for theme in theme_list %}
        <tr>
            <td>
                <br>
                {{ theme.location_category }}
            </td>
            <td>
                <a href="{% url 'room:detail' theme.theme_id %}">{{ theme.theme_name }}</a><br>
                <a href={{ theme.home_url }}>{{ theme.cafe_name }}</a>
            </td>
            <td>
                {{ theme.star_stat }}<br>
                {{ theme.diff_stat }}
            </td>
    <!--            <a href="/room/{{ theme.theme_id }}/">{{ theme.theme_name }}</a>-->
            </td>
        {% endfor %}
        </tr>
        {% else %}
        <p>테마가 없습니다.</p>
    {% endif %}
        </tbody>
    </table>
</div>